#!/bin/bash
# Step 9 (launcher): Run CEHR-BERT prediction on the held-out test cohort.
#
# Thin wrapper: invokes the cehrbert finetuning runner in predict-only mode with the
# generated predict config. Config generation, preflight, and verification live in
# 09_predict.py — prefer running that:
#
#     python 09_predict.py
#
# Args:
#   $1 path to the predict config yaml (generated by 09_predict.py).

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
CONFIG_FILE="${1:?usage: 09_predict.sh <predict_config.yaml>}"

echo "Project root: ${PROJECT_ROOT}"
echo "Using predict config: ${CONFIG_FILE}"
echo ""

cd "${PROJECT_ROOT}"
python -m cehrbert.runners.hf_cehrbert_finetune_runner "${CONFIG_FILE}"

echo ""
echo "Done! Predictions saved under the configured output_dir/test_predictions/"
